[tool.uv]
cache-dir = "./.uv_cache"

[browser]
gatherUsageStats = false

[project]
name = "1cijferho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.12.1",
    "numpy>=2.2.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "polars>=1.21.0",
    "pyjanitor>=0.31.0",
    "rich>=13.9.4",
    "ruff>=0.10.0",
    "streamlit>=1.41.1",
    "streamlit-extras>=0.6.0",
    "xlsxwriter>=3.2.2",
]
